apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: shadow
  region: us-east-2
  # namespace: dev
managedNodeGroups:
  - name: nodegroup-1
    # instanceType: t2.micro
    instanceType: t3a.small
    minSize: 1
    maxSize: 3
    desiredCapacity: 3
    volumeSize: 15
    volumeType: gp2
    tags:
      env: dev
      node-class: tiny
    # ssh:
    #   publicKeyName: surya-ssh-key
