kind: PersistentVolume
apiVersion: v1
metadata:
  name: my-pv
  # namespace: dev
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/share/data"
---
# apiVersion: storage.k8s.io/v1
# kind: StorageClass
# metadata:
#   name: slow
# provisioner: kubernetes.io/gce-pd
# parameters:
#   type: pd-standard
