---
# Source: argonaut-configs/templates/poddisruptionbudget.yaml
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: "hasura-pdb"
spec:
  maxUnavailable: 25%
  selector:
    matchLabels:
      app: "hasura"
---
# Source: argonaut-configs/templates/service.yaml
kind: Service
apiVersion: v1
metadata:
  name: "hasura"
  labels:
    heritage: "Helm"
    release: "RELEASE-NAME"
    chart: "argonaut-configs"
    version: "v1"
    app: "hasura"
spec:
  type: ClusterIP
  selector:
    release: "RELEASE-NAME"
    chart: "argonaut-configs"
    app: "hasura"
  ports: 
    - name: "hasur-hs8080"
      protocol: TCP # UDP and SCTP are the other options
      port: 8080
---
# Source: argonaut-configs/templates/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hasura
  labels:
    heritage: "Helm"
    release: "RELEASE-NAME"
    chart: "argonaut-configs"
    app: "hasura"
    version: "v1"
  annotations:
    {}
spec:
  serviceName: hasura
  selector:
    matchLabels:
      app: "hasura"
  replicas: 1
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      name: "hasura"
      labels:
        heritage: "Helm"
        release: "RELEASE-NAME"
        chart: "argonaut-configs"
        app: "hasura"
      annotations:
        
    spec:
      securityContext:
        {}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - "hasura"
      terminationGracePeriodSeconds: 120
      # Mount Secrets
      volumes:
      # Persistence Enabled - volume mounts
      # extraConfig
      imagePullSecrets:
        - name: image-pull-secret
      initContainers:

      containers:
      - name: "argonaut-configs"
        securityContext:
          {}
        image: "hasura/graphql-engine:v1.3.3"
        imagePullPolicy: "IfNotPresent"

        ports:
        - name: "hasur-hs8080"
          containerPort: 8080
          # protocol: tls
        resources:
          requests:
            cpu: 100m
            memory: 200M
        env:
          - name: HASURA_GRAPHQL_DATABASE_URL
            value: postgres://postgres:bitabeam@postgresql.dev.svc.cluster.local:5432/postgres
          - name: HASURA_GRAPHQL_ENABLE_CONSOLE
            value: "true"
          - name: HASURA_GRAPHQL_DEV_MODE
            value: "true"
        # initContainer volume mount needs to be enabled in the template
        volumeMounts: []
---
# Source: argonaut-configs/templates/ingress.yaml
# Configure Virtual Services
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: "hasura-hs8080-vs"
  labels:
    heritage: "Helm"
    release: "RELEASE-NAME"
    chart: "argonaut-configs"
    app: "hasura"
spec:
  hosts:
    - aws.tritonhq.io
  gateways:
    - istio-system/ingress-gateway
  exportTo:
    - "*" # TBD - env interaction
  http:
    - match:
        - uri:
            prefix: /hasura/
      rewrite:
        uri: "/" # /hasura/
      route:
        - destination:
            port:
              number: 8080
            host: "hasura.dev.svc.cluster.local"
