name: "Argonaut App Actions"
description: "Greetings from the Argonauts!"
author: Surya Oruganti
inputs:
  who-to-greet: # id of input
    description: "Who to greet"
    required: true
    default: "Jason"
  aws-access-key-id:
    description: "AWS Access Key ID"
    required: true
    default: ""
  aws-secret-access-key:
    description: "AWS Secret Access Key"
    required: true
    default: ""
  docker-image-repository:
    description: "Docker Image Repository"
    required: true
    default: ""
  docker-image-digest:
    description: "Docker Image Digest"
    required: true
    default: ""
  gh-username:
    description: "GitHub username"
    required: true
    default: ""
  gh-access-token:
    description: "GitHub access token"
    required: true
    default: ""
outputs:
  time-now:
    description: "Time Now"
    value: ${{ steps.current-time.outputs.time-now }}
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.who-to-greet }} # $1
    - ${{ inputs.aws-access-key-id }} # $2
    - ${{ inputs.aws-secret-access-key }} # $3
    - ${{ inputs.docker-image }} # $4
    - ${{ inputs.docker-image-tag }} # $5
    - ${{ inputs.docker-image-access-token }} # $6
    - ${{ inputs.git-username }} # $7
    - ${{ inputs.git-access-token }} # $8
    - ${{ inputs.docker-image-digest }} # $5
branding:
  icon: "server"
  color: "purple"
