name: "Argonaut Actions"
description: "Greetings from the Argonauts!"
author: Surya Oruganti
inputs:
  who-to-greet: # id of input
    description: "Who to greet"
    required: true
    default: "Jason"
outputs:
  time-now:
    description: "Time Now"
    value: ${{ steps.current-time.outputs.time-now }}
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.who-to-greet }}
branding:
  icon: "server"
  color: "purple"
