---
# Source: argonaut-configs/templates/poddisruptionbudget.yaml
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: "myappname-pdb"
spec:
  maxUnavailable: 25%
  selector:
    matchLabels:
      app: "myappname"
---
# Source: argonaut-configs/templates/service.yaml
kind: Service
apiVersion: v1
metadata:
  name: "myappname"
  labels:
    heritage: "Helm"
    release: "RELEASE-NAME"
    chart: "argonaut-configs"
    version: "v1"
    app: "myappname"
spec:
  type: ClusterIP
  selector:
    release: "RELEASE-NAME"
    chart: "argonaut-configs"
    app: "myappname"
  ports: 
    - name: "myappname-device-backend-3333"
      protocol: TCP # UDP and SCTP are the other options
      port: 3333 
    - name: "myappname-hasura-8080"
      protocol: TCP # UDP and SCTP are the other options
      port: 8080 
    - name: "myappname-mqtt-8883"
      protocol: TCP # UDP and SCTP are the other options
      port: 8883 
    - name: "myappname-mqtt-1883"
      protocol: TCP # UDP and SCTP are the other options
      port: 1883
---
# Source: argonaut-configs/templates/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: myappname
  labels:
    heritage: "Helm"
    release: "RELEASE-NAME"
    chart: "argonaut-configs"
    app: "myappname"
    version: "v1"
  annotations:
    {}
spec:
  serviceName: myappname
  selector:
    matchLabels:
      app: "myappname"
  replicas: 2
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      name: "myappname"
      labels:
        heritage: "Helm"
        release: "RELEASE-NAME"
        chart: "argonaut-configs"
        app: "myappname"
      annotations:
        
    spec:
      securityContext:
        {}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - "myappname"
      terminationGracePeriodSeconds: 120
      # Mount Secrets
      volumes:
      # Persistence Enabled - volume mounts
      # extraConfig
      imagePullSecrets:
        - name: image-pull-secret
      initContainers:

      containers:
      - name: "argonaut-configs"
        securityContext:
          {}
        image: "wordpress:latest"
        imagePullPolicy: "IfNotPresent"

        ports:
        - name: "myappname-device-backend-3333"
          containerPort: 3333
          # protocol: tls
          # ingress: true
        - name: "myappname-hasura-8080"
          containerPort: 8080
          # protocol: tls
          # ingress: true
        - name: "myappname-mqtt-8883"
          containerPort: 8883
          # protocol: tcp
          # ingress: true
        - name: "myappname-mqtt-1883"
          containerPort: 1883
          # protocol: tcp
          # ingress: true
        resources:
          requests:
            cpu: 100m
            memory: 200M
        env:
        # initContainer volume mount needs to be enabled in the template
        volumeMounts: []
---
# Source: argonaut-configs/templates/ingress.yaml
# Configure Virtual Services
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: "myappname-device-backend-3333-vs"
  labels:
    heritage: "Helm"
    release: "RELEASE-NAME"
    chart: "argonaut-configs"
    app: "myappname"
spec:
  hosts:
    - aws.tritonhq.io
  gateways:
    -   name: ingress-gateway
  exportTo:
    - "*" # TBD - env interaction
  http:
    - match:
        - uri:
            prefix: /device-backend/
      route:
        - destination:
            port:
              number: 443
            host: "myappname.dev.svc.cluster.local"
---
# Source: argonaut-configs/templates/ingress.yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: "myappname-hasura-8080-vs"
  labels:
    heritage: "Helm"
    release: "RELEASE-NAME"
    chart: "argonaut-configs"
    app: "myappname"
spec:
  hosts:
    - aws.tritonhq.io
  gateways:
    -   name: ingress-gateway
  exportTo:
    - "*" # TBD - env interaction
  http:
    - match:
        - uri:
            prefix: /hasura/
      route:
        - destination:
            port:
              number: 443
            host: "myappname.dev.svc.cluster.local"
---
# Source: argonaut-configs/templates/ingress.yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: "myappname-mqtt-8883-vs"
  labels:
    heritage: "Helm"
    release: "RELEASE-NAME"
    chart: "argonaut-configs"
    app: "myappname"
spec:
  hosts:
    - aws.tritonhq.io
  gateways:
    -   name: ingress-gateway
  exportTo:
    - "*" # TBD - env interaction
  # tcp implementation
  tcp:
  - match:
    - port: 8883
    route:
    - destination:
        host: "myappname.dev.svc.cluster.local"
        port:
          number: 8883
---
# Source: argonaut-configs/templates/ingress.yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: "myappname-mqtt-1883-vs"
  labels:
    heritage: "Helm"
    release: "RELEASE-NAME"
    chart: "argonaut-configs"
    app: "myappname"
spec:
  hosts:
    - aws.tritonhq.io
  gateways:
    -   name: ingress-gateway
  exportTo:
    - "*" # TBD - env interaction
  # tcp implementation
  tcp:
  - match:
    - port: 1883
    route:
    - destination:
        host: "myappname.dev.svc.cluster.local"
        port:
          number: 1883
