externalServices:
  - name: rds-mysql-external
    hosts:
      - database-1.co45pjczxgry.us-east-2.rds.amazonaws.com
    # addresses:
    #   - 10.10.10.0/24
    ports:
      - number: 3306
        name: mysql
        protocol: TCP
      # - number: 443
      #   name: https
      #   protocol: HTTPS
    resolution: NONE # DNS
    location: MESH_EXTERNAL
    # tls: Disabled   # TO BE IMPLEMENTED
