---
metadata:
  annotations: # application specific
    argocd.argoproj.io/sync-options: Prune=false
    # argocd.argoproj.io/compare-options: IgnoreExtraneous

spec: # ArgoCD instance specific
  syncPolicy:
    automated:
      prune: false # Conservative, Debatable
      selfHeal: false # Conservative, Debatable
